import os
import smtplib
import pandas as pd
from datetime import datetime, timedelta
from email.mime.image import MIMEImage
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email import encoders
from email.mime.text import MIMEText
from email.utils import make_msgid

import utilities


global sent_alerts
sent_alerts = 0


def attach_file(message, full_file_path):
    filename = full_file_path
    attachment = open(filename, "rb")
    # instance of MIMEBase and named as p
    p = MIMEBase('application', 'octet-stream')
    # To change the payload into encoded form
    p.set_payload((attachment).read())
    # encode into base64
    encoders.encode_base64(p)
    p.add_header('Content-Disposition', "attachment; filename= %s" % os.path.basename(filename))
    # attach the instance 'p' to instance 'msg'
    message.attach(p)
    return message


def create_and_send_message(to_email, forecast_settings, file_date):
    msg = MIMEMultipart()
    smtp_settings = forecast_settings["smtp_settings"]
    # Your gmail credentials
    username = smtp_settings["user"]
    password = smtp_settings["password"]

    # Email details
    msg['To'] = to_email
    msg['Subject'] = "BEWA Alerts for " + file_date
    body = """\
    <html>
    <head>
    </head>
    <body>
        <table cellspacing="0" cellpadding="4" style="max-width:600px">
            <tbody>
                <tr>
                    <td>
                        <h1>
                            High Impact Weather Assessment Toolkit (HIWAT) and
                            Bangladesh Extreme Weather Alert (BEWA) Automated Alert
                        </h1>
                    </td>
                </tr>
                <tr>
                    <td>
                        <table>
                            <tr>
                                <td>
                                    <p>
                                        <span style='font-weight:bold;'>High-Impact Weather Assessment Toolkit (HIWAT) </span>
                                        was developed to facilitate probabilistic forecasting and to assess the hazards associated with high-impact weather.
                                    </p>
                                    <p>
                                        HIWAT is a real-time, convection-permitting ensemble numerical weather prediction system based on the Weather
                                        Research and Forecasting (WRF) model and a situational awareness tool that gauges thunderstorm intensity
                                        through satellite measurements
                                    </p>
                                    <p>
                                        For the Bangladesh Meteorological Department (BMD) Baishakhi High Performance Computing (HPC) HIWAT instance,
                                        the WRF model is configured using an outer domain with 12-km grid spacing centered on South Asia, a 4-km inner
                                        domain that is centered on Bangladesh.
                                    </p>
                                    <p>
                                        The primary products generated by HIWAT are <span style='font-weight:bold;'>48 hour probabilistic</span>
                                        forecasts of the <span style='font-weight:bold;'>thunderstorm</span> hazards associated
                                        with tornadoes, damaging <span style='font-weight:bold;'>wind</span> and <span style='font-weight:bold;'>
                                            hail
                                        </span>, frequent <span style='font-weight:bold;'>lightning</span>, and intense <span style='font-weight:bold;'>
                                            rainfall
                                        </span>. These are provided at each hour
                                        of the forecast cycle and temporally composited into daily summary probability maps that can readily facilitate
                                        the outlooks of thunderstorm hazards.
                                    </p>
                                    <p>
                                        <span style='font-weight:bold;'>Background</span>: For further HIWAT modeling details see (
                                        <a href='https://library.oapen.org/bitstream/handle/20.500.12657/50712/978-3-030-73569-2.pdf?sequence=1#page=256'>
                                            Gatlin et al. 2021
                                        </a>)
                                    </p>
                                    <p>
                                        <span style='font-weight:bold;'>Bangladesh Extreme Weather Alert (BEWA)</span>
                                        <a href='https://github.com/SERVIR/Bangladesh-Extreme-Weather-Alert'>system</a> and
                                        <a href='https://bewa.servirglobal.net/'>output archive</a> provides
                                        an automated weather alert to rapidly enable forecast dissemination. This email is generated via BEWA.
                                    </p>
                                    <p>
                                        <span style='font-weight:bold;'>Disclaimer</span>: The HIWAT system is an experimental forecasting tool which
                                        provides probabilistic forecasts. All use and decision-making employing the data products should be
                                        applied with discretion.
                                    </p>
                                    <p>
                                        <span style='font-weight:bold;'>Credit</span>: The Modeling system and alert were developed and produced from a
                                        collaboration among  Bangladesh Meteorological Department, International Centre for Integrated Mountain Development,
                                        (ICIMOD), and  NASA SERVIR
                                    </p>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <table>
    
                                        <tr>
                                            <td style="vertical-align:bottom">
                                                Dr. Md. Abdul Mannan<br />
                                                Deputy Director of Bangladesh Meteorological Department<br />
                                                mannan_u2003@yahoo.co.in<br />
                                            </td>
                                            <td>
                                                <br /><img src="cid:%s" style="max-height:150px;" />
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>
                <tr>
                    <td>
                        <table>
                            <tr>
                                <td>
                                    <h1>
                                        হাই ইমপ্যাক্ট ওয়েদার অ্যাসেসমেন্ট টুলকিট (হাইওয়াট/HIWAT) এবং
                                        বাংলাদেশের চরমভাবাপন্নআবহাওয়ার স্বয়ংক্রিয় সতর্কত সংকেত  (BEWA)
                                    </h1>
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>
                <tr>
                    <td>
                        <table>
                            <tr>
                                <td>
                                    <p>
                                        চরমভাবাপন্ন আবহাওয়া পর্যবেক্ষণটুলকিট (HIWAT) দুর্যোগপূর্ণ আবহাওয়া পূর্বাভাস সহজভাবে প্রদান করার  জন্য এবং দুর্যোগপূর্ণ আবহাওয়ার সাথে সম্পর্কিত বিপদগুলি মূল্যায়ন করার জন্য তৈরি করা হয়েছে।
                                    </p>
                                    <p>হাইওয়াট আবহাওয়া গবেষণা ও পূর্বাভাস (WRF) মডেলের উপর ভিত্তি করে একটি সময়মত, পরিচলন-অনুমতি প্রদানকারী সংখ্যাসূচক আবহাওয়ার পূর্বাভাস পদ্ধতিএবং একটি পরিস্থিতিগত সচেতনতা সরঞ্জাম যা উপগ্রহ পরিমাপের মাধ্যমে বজ্রপাতের তীব্রতা পরিমাপ করে।
                                   
                                   </p>
                                    <p>বাংলাদেশ আবহাওয়া অধিদপ্তর (বিএমডি) বৈশাখী হাই পারফরম্যান্স কম্পিউটিং (এইচপিসি) HIWAT উদাহরণের জন্য, WRF মডেলটি দক্ষিণ এশিয়াকে কেন্দ্র করে 12-কিমি গ্রিড ব্যবধান সহ একটি বাইরের ডোমেন ব্যবহার করে কনফিগার করা হয়েছে, একটি 4-কিমি অভ্যন্তরীণ ডোমেন যা বাংলাদেশকে কেন্দ্র করে।
                                    
                                    </p>
                                    <p>
    হাইওয়াট প্রধানত টর্নেডো, বাতাসের তীব্রতা এবং শিলাবৃষ্টি, বজ্রপাতের প্রকোপ এবং ভারীবৃষ্টিপাতের সাথে যুক্ত বজ্রঝড়ের ৪৮ ঘণ্টা পূর্বে সম্ভাব্য পূর্বাভাস দিয়ে থাকে। এগুলি পূর্বাভাস প্রক্রিয়ার প্রতিটি ঘন্টায় সরবরাহ করা হয় এবং সাময়িকভাবে দৈনিক সারাংশ সম্ভাব্যতার মানচিত্রে উপস্থাপন করা হয় যা সহজেই বজ্রঝড়ের ঝুঁকির দৃষ্টিভঙ্গি সহজতর করতে পারে।
    </p>
                                    <p>
                                        <span style='font-weight:bold;'> পটভূমি</span>: হাইওয়াট মডেলিং বিশদ বিবরণের জন্য দেখুন ( <a href='https://library.oapen.org/bitstream/handle/20.500.12657/50712/978-3-030-73569-2.pdf?sequence=1#page=256'>
                                            Gatlin et al. 2021
                                        </a>)
                                    </p>
                                    <p>
    বাংলাদেশ চরমভাবাপন্ন (BEWA) পদ্ধতিএবং আউটপুট আর্কাইভ দ্রুত পূর্বাভাস প্রচার করতে সক্ষম করার জন্য একটি স্বয়ংক্রিয় আবহাওয়া সতর্কতা প্রদান করে। এই ইমেলটি BEWA এর মাধ্যমে তৈরি করা হয়েছে।</p>
                                    
                                    <p>
                                        <span style='font-weight:bold;'>
    দায়-ঘোষণা
    </span>: 
    হাইওয়াটএকটি পরীক্ষামূলক পূর্বাভাস পদ্ধতিযা চরমভাবাপন্ন আবহাওয়ার সম্ভাব্য পূর্বাভাস প্রদান করে। তথ্য ব্যবহার করার সময় ব্যবহারকারী তাদের নিজস্ব চিন্তাভাবনা এবং বিবেচনা  করা উচিত।</p>
                                    <p>
                                        <span style='font-weight:bold;'> কৃতজ্ঞতা</span>: হাইওয়াট মডেলিং পদ্ধতিএবং সতর্কতা বাংলাদেশ আবহাওয়া অধিদপ্তর, ইন্টারন্যাশনাল সেন্টার ফর ইন্টিগ্রেটেড মাউন্টেন ডেভেলপমেন্ট, (ICIMOD), এবং NASA SERVIR-এর যৌথ সহযোগিতায় তৈরি করা হয়েছে।
                                    </p>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <table>
                                        <tr>
                                            <td style="vertical-align:bottom">
                                                ড. মোঃ আব্দুল মান্নান <br />
                                                উপ-পরিচালক, বাংলাদেশ আবহাওয়া অধিদপ্তর <br />
                                                mannan_u2003@yahoo.co.in<br />
                                            </td>
                                            <td>
                                                <br /><img src="cid:%s" style="max-height:150px;" />
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>
    
            </tbody>
        </table>
    </body>
    </html>
    """

    image_cid = make_msgid(domain='icimod.org')

    dir_path = os.path.dirname(os.path.realpath(__file__))
    msg.attach(MIMEText(body % ("logo.png", "logo.png"), 'html'))
    output_directory = forecast_settings["forecasts"][0]["output_directory"]
    attachment_count = 0
    for filename in os.listdir(output_directory):
        # if output dirs are different we'll need all, i will add a check in the next iteration
        if file_date in filename:
            attachment_count = attachment_count + 1
            f = os.path.join(output_directory, filename)
            # checking if it is a file
            if os.path.isfile(f):
                msg = attach_file(msg, f)

    if attachment_count > 0:
        with open(os.path.join(dir_path, "logo.png"), 'rb') as fp:
            img = MIMEImage(fp.read())
        img.add_header('Content-ID', '<{}>'.format("logo.png"))
        msg.attach(img)

        # Send the email
        with smtplib.SMTP_SSL(smtp_settings["smtp"], 465) as server:
            server.login(username, password)
            server.sendmail(username, msg['To'], msg.as_string())
        global sent_alerts
        sent_alerts = sent_alerts + 1


def send_alerts(delta_days):
    try:
        file_date = (datetime.today() - timedelta(days=delta_days)).strftime('%Y%m%d')
        print(file_date)
        forecast_definitions = utilities.get_forecast_definitions()
        email_list = pd.read_excel(forecast_definitions["email_list_xlsx"])
        emails = email_list["Email"]
        for email in emails:
            try:
                create_and_send_message(email, forecast_definitions, file_date)
            except Exception as e:
                print(str(e))

        global sent_alerts
        if sent_alerts > 0:
            print(str(sent_alerts) + " email alerts were sent")
            sent_alerts = 0
            return True
        else:
            print("No alerts were sent, please check to confirm the data was available.")
            return False
    except Exception as e:
        print("Sending alerts failed, please check to confirm data exists.  The following is the system error: " + str(e))
        sent_alerts = 0
        return False

